using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LocalRAG.Entities.PersonalTrip
{
    /// <summary>
    /// 개인 여행의 개별 일정 항목
    /// </summary>
    public class ItineraryItem
    {
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// N일차 (e.g., 1, 2, 3...)
        /// </summary>
        [Required]
        public int DayNumber { get; set; }

        /// <summary>
        /// 장소명 (e.g., "에펠탑", "루브르 박물관")
        /// </summary>
        [Required]
        [MaxLength(200)]
        public string LocationName { get; set; } = string.Empty;

        /// <summary>
        /// 주소
        /// </summary>
        [MaxLength(500)]
        public string? Address { get; set; }

        /// <summary>
        /// 위도
        /// </summary>
        public double? Latitude { get; set; }

        /// <summary>
        /// 경도
        /// </summary>
        public double? Longitude { get; set; }

        /// <summary>
        /// Google Place ID
        /// </summary>
        [MaxLength(300)]
        public string? GooglePlaceId { get; set; }

        /// <summary>
        /// 시작 시간
        /// </summary>
        public TimeOnly? StartTime { get; set; }

        /// <summary>
        /// 종료 시간
        /// </summary>
        public TimeOnly? EndTime { get; set; }

        /// <summary>
        /// 정렬 순서 (같은 날짜 내에서)
        /// </summary>
        public int OrderNum { get; set; }

        /// <summary>
        /// 메모
        /// </summary>
        [MaxLength(2000)]
        public string? Notes { get; set; }

        /// <summary>
        /// 카테고리 (e.g., "음식점", "쇼핑", "관광")
        /// </summary>
        [MaxLength(100)]
        public string? Category { get; set; }

        /// <summary>
        /// 전화번호
        /// </summary>
        [MaxLength(50)]
        public string? PhoneNumber { get; set; }

        /// <summary>
        /// 카카오맵 장소 URL
        /// </summary>
        [MaxLength(500)]
        public string? KakaoPlaceUrl { get; set; }

        /// <summary>
        /// 비용 금액 (선택사항)
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal? ExpenseAmount { get; set; }

        /// <summary>
        /// 자동 생성된 일정 항목인지 여부 (예: 숙소 체크인/체크아웃)
        /// </summary>
        public bool IsAutoGenerated { get; set; } = false;

        // Foreign Key
        [Required]
        public int PersonalTripId { get; set; }

        // Navigation property
        [ForeignKey(nameof(PersonalTripId))]
        public virtual PersonalTrip PersonalTrip { get; set; } = null!;
    }
}
