// <auto-generated />
using System;
using LocalRAG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalRAG.Migrations
{
    [DbContext(typeof(ConventionDbContext))]
    [Migration("20260323071500_AddScheduleImage")]
    partial class AddScheduleImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Uses snapshot from ConventionDbContextModelSnapshot
        }
    }
}
